environment:
  OPENSSL_LIBS: ssleay32:libeay32
  matrix:
  # 64-bit MSVC builds currently hang when trying to run the coverage crate
  # lib test. Suppressed this configuration for now to allow for the overall
  # build to succeed
  # - TARGET: x86_64-pc-windows-msvc
  #  BITS: 64
  - TARGET: i686-pc-windows-msvc
    BITS: 32
  - TARGET: i686-pc-windows-gnu
    BITS: 32
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - SET OPENSSL_INCLUDE_DIR=C:\OpenSSL-Win%BITS%\include
  - SET OPENSSL_LIB_DIR=C:\OpenSSL-Win%BITS%\lib
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
