[package]
name = "find-unimplemented-tasks"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Rosetta_Code/Find_unimplemented_tasks"

[dependencies]
hyper = "0.9.3"
rustc-serialize = "0.3"
url = "1.1.0"
