[package]
name = "https"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/HTTPS"

[dependencies.reqwest]
git = "https://github.com/seanmonstar/reqwest"
default-features = false
features = ["tls"]
